name: Build Rnotes

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y libwebkit2gtk-4.1-dev \
          build-essential \
          curl \
          wget \
          file \
          libxdo-dev \
          libssl-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev

      - name: Install Rust target
        run: rustup target add x86_64-unknown-linux-gnu

      - name: Install Tauri CLI
        run: cargo install tauri-cli 

      - name: Build project
        run: cargo tauri build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-bundle
          path: src-tauri/target/release/bundle/

  build-macos:
    name: Build on macOS
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Rust target
        run: rustup target add aarch64-apple-darwin

      - name: Install Tauri CLI
        run: cargo install tauri-cli 

      - name: Build project
        run: cargo tauri build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-bundle
          path: src-tauri/target/release/bundle/

  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install MSVC++
        run: |
          choco install -y visualstudio2022buildtools visualstudio2022-workload-vctools
        shell: powershell

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Tauri CLI
        run: cargo install tauri-cli 

      - name: Build project
        run: cargo tauri build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-bundle
          path: src-tauri/target/release/bundle/ 
